### ISSUE TITLE
Dark Theme: Blog tags do not save on creation of post

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#170]
This issue is happening consistently for all of us so is easily re-created.

When a blog post is being created, the tag field can be populated, but when the post is saved, the tag doesn't get saved with it.

If you go to the edit screen of an already-existing post, you can update the tag field and it gets saved just fine.

Can this be fixed so that the tag that is entered on the create screen gets saved?

**Comment by acavanagh** [comment]
I believe that this is fixed now.  Please review.

**Comment by meetinghouse** [comment]
Yes, it does work now. However, I notice that when I tested this, I created a post called "test" and created a tag "test." That all worked fine, but after I delete the post, that "test" tag is still appearing in the left nav. That doesn't seem right... I don't think any tags that have no published posts connected with them should show up there.

**Comment by acavanagh** [comment]
The tags should be deleted with the post, but I'll check to make sure.

**Comment by meetinghouse** [comment]
The original issue has been resolved, although I will create a new issue for some newly discovered bugs in the blog post tags and reference this one. Thanks!
